import { Inter } from "next/font/google";
import "./globals.css";
import { DarkModeToggle } from "@/components/DarkModeToggle";
import { DarkModeProvider } from "@/components/DarkModeProvider";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( { children } ) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <DarkModeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="!min-w-full flex flex-col p-12 px-16 items-start justify-start">
            <nav className="w-full mb-14 flex justify-between">
              <h1 className="font-black text-4xl">Ray's Shadcn Practice</h1>
              <DarkModeToggle />
            </nav>
            { children }
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
