import { Inter } from "next/font/google";
import "./globals.css";
import { DarkModeToggle } from "@/components/DarkModeToggle";
import { DarkModeProvider } from "@/components/DarkModeProvider";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

import Link from "next/link";
import CustomLink from "@/components/CustomLink";
import { AlignJustify } from "lucide-react";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const fetchAnime = async () => {

  // const topAiring = await fetch( "https://anime-api-liart.vercel.app/top-airing", { method: "POST" } );
  const recentEpisodes = await fetch( "https://anime-api-liart.vercel.app/recent-episodes", { method: "POST" } );

  return {
    // topAiring: ( await topAiring.json() ),
    recentEpisodes: ( await recentEpisodes.json() )
  };

};


export default async function RootLayout ( { children } ) {

  const { recentEpisodes } = await fetchAnime();

  return (
    <html lang="en">
      <body className={ inter.className }>
        <DarkModeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="!min-w-full flex flex-col p-10 md:px-16 items-start justify-start">
            <nav className="w-full mb-14 flex justify-between items-center">
              <h1 className="font-black text-xl md:text-4xl">RayAnime: Enjoy</h1>
              <div className="flex gap-14 items-center md:items-baseline">
                <div className="gap-5 text-sm hidden md:flex">
                  <CustomLink key={ "/" } href="/" className={ `py-1 px-3 relative before:transition-all before:origin-left before:duration-300 before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-muted before:-z-10 before:scale-x-0 before:hover:scale-x-100` } active={ "before:!scale-100" }>Shadcn</CustomLink>
                  <CustomLink key={ "/movies" } href="/movies" className={ `py-1 px-3 relative before:transition-all before:origin-left before:duration-300 before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-muted before:-z-10 before:scale-x-0 before:hover:scale-x-100` } active={ "before:!scale-100" }>Aceternity</CustomLink>
                </div>
                <DropdownMenu className="md:hidden">
                  <DropdownMenuTrigger asChild className="md:hidden">
                    <Button variant="outline" size="icon">
                      <AlignJustify />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>
                      <CustomLink key={ "/" } href="/" className={ `py-1 px-3 relative before:transition-all before:origin-left before:duration-300 before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-muted before:-z-10 before:scale-x-0 before:hover:scale-x-100` } active={ "" }>Shadcn</CustomLink>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <CustomLink key={ "/movies" } href="/movies" className={ `py-1 px-3 relative before:transition-all before:origin-left before:duration-300 before:absolute before:left-0 before:top-0 before:w-full before:h-full before:bg-muted before:-z-10 before:scale-x-0 before:hover:scale-x-100` } active={ "" }>Aceternity</CustomLink>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <DarkModeToggle />
              </div>
            </nav>
            <div className="w-full max-w-full flex gap-8">
              { children }

            </div>
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
